# Generated by Django 5.1.4 on 2025-01-11 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operations', '0001_initial'),
        ('souscriptions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompteBancaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Code unique identifiant le compte bancaire', max_length=50, verbose_name='Code du compte')),
                ('nom', models.CharField(help_text='Nom descriptif du compte bancaire', max_length=200, verbose_name='Nom du compte')),
                ('description', models.TextField(blank=True, help_text='Description détaillée du compte bancaire', null=True, verbose_name='Description')),
                ('code_banque', models.CharField(help_text="Code d'identification de la banque", max_length=50, verbose_name='Code banque')),
                ('code_guichet', models.CharField(help_text='Code du guichet bancaire', max_length=50, verbose_name='Code guichet')),
                ('numero_compte', models.CharField(help_text='Numéro unique du compte bancaire', max_length=50, verbose_name='Numéro de compte')),
                ('rib', models.CharField(help_text="Relevé d'Identité Bancaire complet", max_length=100, verbose_name='RIB')),
                ('image', models.ImageField(blank=True, help_text='Image ou document associé au compte bancaire', null=True, upload_to='comptes_bancaires/', verbose_name='Image du compte')),
                ('actif', models.BooleanField(default=True, help_text='Indique si le compte bancaire est actuellement actif', verbose_name='Compte actif')),
            ],
            options={
                'verbose_name': 'Compte Bancaire',
                'verbose_name_plural': 'Comptes Bancaires',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='ModePaiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='Code du mode de paiement')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom du mode de paiement')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Mode de Paiement',
                'verbose_name_plural': 'Modes de Paiement',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Quittance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Code unique identifiant la quittance', max_length=50, verbose_name='Code de la quittance')),
                ('numero_transaction', models.CharField(help_text='Numéro unique de la transaction', max_length=100, verbose_name='Numéro de transaction')),
                ('numero_quittance', models.CharField(help_text='Numéro de quittance officiel', max_length=100, verbose_name='Numéro de quittance')),
                ('souscripteur', models.CharField(help_text='Nom complet du souscripteur', max_length=200, verbose_name='Nom du souscripteur')),
            ],
            options={
                'verbose_name': 'Quittance',
                'verbose_name_plural': 'Quittances',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_paiement', models.DateTimeField(auto_now_add=True, verbose_name='Date de Paiement')),
                ('numero_paiement', models.CharField(max_length=100, verbose_name='Numéro de Paiement')),
                ('numero_transaction', models.CharField(max_length=100, verbose_name='Numéro de Transaction')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Montant')),
                ('statut', models.CharField(choices=[('en_attente', 'En Attente'), ('confirme', 'Confirmé'), ('rejete', 'Rejeté'), ('rembourse', 'Remboursé')], default='en_attente', max_length=50, verbose_name='Statut du Paiement')),
                ('commentaire', models.TextField(blank=True, null=True, verbose_name='Commentaire')),
                ('date_confirmation', models.DateTimeField(blank=True, null=True, verbose_name='Date de Confirmation')),
                ('mode_paiement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='paiements.modepaiement', verbose_name='Mode de Paiement')),
                ('reference_operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements', to='operations.operations', verbose_name='Opération Associée')),
                ('souscripteur_morale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='souscriptions.souscripteurmorale', verbose_name='Souscripteur Morale')),
                ('souscripteur_physique', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='souscriptions.souscripteurphysique', verbose_name='Souscripteur Physique')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-date_paiement'],
            },
        ),
    ]
