# Generated by Django 5.1.4 on 2025-01-11 11:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paiements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='utilisateur_confirmation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_confirmes', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur de Confirmation'),
        ),
        migrations.AddConstraint(
            model_name='paiement',
            constraint=models.CheckConstraint(condition=models.Q(('souscripteur_physique__isnull', False), ('souscripteur_morale__isnull', False), _connector='OR'), name='souscripteur_not_null'),
        ),
    ]
