# Generated by Django 5.1.4 on 2025-01-11 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Quittance',
        ),
        migrations.RenameField(
            model_name='paiement',
            old_name='montant',
            new_name='montant_souscription',
        ),
        migrations.RemoveField(
            model_name='paiement',
            name='commentaire',
        ),
        migrations.RemoveField(
            model_name='paiement',
            name='reference_operation',
        ),
        migrations.RemoveField(
            model_name='paiement',
            name='utilisateur_confirmation',
        ),
    ]
