# Generated by Django 5.1.4 on 2025-01-11 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0003_delete_quittance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paiement',
            name='date_confirmation',
        ),
    ]
