# Generated by Django 5.1.4 on 2025-01-11 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0004_remove_paiement_date_confirmation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paiement',
            name='numero_paiement',
        ),
    ]
