# Generated by Django 5.1.4 on 2025-01-11 11:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Code de la condition')),
                ('intitule', models.CharField(max_length=200, verbose_name='Intitulé de la condition')),
                ('condition_souscription', models.TextField(help_text='Décrivez les conditions requises pour la souscription', verbose_name='Conditions de souscription')),
                ('methode_attribution', models.TextField(help_text="Décrivez la méthode utilisée pour l'attribution", verbose_name="Description de la méthode d'attribution")),
                ('documents_requis', models.TextField(help_text='Listez tous les documents nécessaires', verbose_name='Description des documents à fournir')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('actif', models.BooleanField(default=True, verbose_name='Condition active')),
            ],
            options={
                'verbose_name': 'Condition',
                'verbose_name_plural': 'Conditions',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='ListesParcelles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, verbose_name='Code de la parcelle')),
                ('site', models.CharField(max_length=100, verbose_name='Site')),
                ('zone', models.CharField(max_length=100, verbose_name='Zone')),
                ('section', models.CharField(max_length=100, verbose_name='Section')),
                ('lot', models.CharField(max_length=100, verbose_name='Lot')),
                ('parcelle', models.CharField(max_length=100, verbose_name='Parcelle')),
                ('surface', models.IntegerField(verbose_name='Surface')),
                ('cout_m2', models.IntegerField(verbose_name='Coût au m²')),
                ('acompte', models.IntegerField(verbose_name='Acompte')),
                ('reste_a_payer', models.IntegerField(verbose_name='Reste à payer')),
                ('cout_total', models.IntegerField(verbose_name='Coût total')),
                ('paye', models.BooleanField(default=False, verbose_name='Payé')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('bloquer', models.BooleanField(default=False, verbose_name='Bloqué')),
                ('date_ajout', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date d'ajout")),
            ],
            options={
                'verbose_name': 'Liste des Parcelles',
                'verbose_name_plural': 'Listes des Parcelles',
                'ordering': ['site', 'zone', 'parcelle', '-date_ajout'],
            },
        ),
        migrations.CreateModel(
            name='Localite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='Code de la localité')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom de la localité')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description de la localité')),
                ('actif', models.BooleanField(default=True, verbose_name='Localité active')),
            ],
            options={
                'verbose_name': 'Localité',
                'verbose_name_plural': 'Localités',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Operations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='Code')),
                ('intitule', models.CharField(max_length=200, verbose_name='Intitulé')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('date_debut_operation', models.DateField(default=django.utils.timezone.now, verbose_name="Date de début de l'opération")),
                ('date_fin_operation', models.DateField(blank=True, null=True, verbose_name="Date de fin de l'opération")),
                ('duree_depot_physique', models.PositiveIntegerField(default=0, verbose_name='Durée pour le dépôt physique (en jours)')),
                ('duree_souscription', models.PositiveIntegerField(default=0, verbose_name="Durée d'une souscription (en minutes)")),
                ('montant_souscription', models.PositiveIntegerField(default=0, verbose_name='Montant de la souscription (FCFA)')),
                ('visuel', models.ImageField(blank=True, null=True, upload_to='operations/visuels/')),
                ('disponible', models.BooleanField(default=False, verbose_name='Rendre disponible')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Opération',
                'verbose_name_plural': 'Opérations',
                'ordering': ['-date_debut_operation'],
            },
        ),
        migrations.CreateModel(
            name='Parcelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cout_m2', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PositionParcelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='Code de la position de parcelle')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom de la position de parcelle')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description de la position de parcelle')),
                ('actif', models.BooleanField(default=True, verbose_name='Position de parcelle active')),
            ],
            options={
                'verbose_name': 'Position de parcelle',
                'verbose_name_plural': 'Positions de parcelles',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='ProcessusAttribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name="Code du processus d'attribution")),
                ('nom', models.CharField(max_length=200, verbose_name="Nom du processus d'attribution")),
                ('description', models.TextField(blank=True, null=True, verbose_name="Description du processus d'attribution")),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('actif', models.BooleanField(default=True, verbose_name="Processus d'attribution actif")),
            ],
            options={
                'verbose_name': "Processus d'attribution",
                'verbose_name_plural': "Processus d'attribution",
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('libelle', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('superficie_origine', models.FloatField(default=0)),
                ('superficie_viabilisee', models.FloatField(default=0)),
                ('actif', models.BooleanField(default=True)),
                ('date_archivage', models.DateTimeField(blank=True, editable=False, null=True)),
                ('archive', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TypeParcelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='Code du type de parcelle')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom du type de parcelle')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description du type de parcelle')),
                ('actif', models.BooleanField(default=True, verbose_name='Type de parcelle actif')),
            ],
            options={
                'verbose_name': 'Type de parcelle',
                'verbose_name_plural': 'Types de parcelles',
                'ordering': ['nom'],
            },
        ),
    ]
