# Generated by Django 5.1.4 on 2025-01-11 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operations', '0001_initial'),
        ('paiements', '0001_initial'),
        ('souscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='operations',
            name='comptes_bancaires',
            field=models.ManyToManyField(related_name='operations', to='paiements.comptebancaire', verbose_name='Comptes bancaires'),
        ),
        migrations.AddField(
            model_name='operations',
            name='condition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations', to='operations.condition', verbose_name='Condition'),
        ),
        migrations.AddField(
            model_name='operations',
            name='parcelles',
            field=models.ManyToManyField(blank=True, related_name='operations_liste', to='operations.listesparcelles', verbose_name='Parcelles'),
        ),
        migrations.AddField(
            model_name='operations',
            name='types_souscripteurs',
            field=models.ManyToManyField(related_name='operations', to='souscriptions.typesouscripteur', verbose_name='Types de souscripteur'),
        ),
        migrations.AddField(
            model_name='listesparcelles',
            name='operation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parcelles_operation', to='operations.operations', verbose_name='Opération'),
        ),
        migrations.AddField(
            model_name='condition',
            name='operation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='operations.operations', verbose_name='Opération'),
        ),
        migrations.AddField(
            model_name='operations',
            name='positions_parcelles',
            field=models.ManyToManyField(blank=True, related_name='operations_positions', to='operations.positionparcelle', verbose_name='Positions de parcelles'),
        ),
        migrations.AddField(
            model_name='listesparcelles',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parcelles_position', to='operations.positionparcelle', verbose_name='Position de parcelle'),
        ),
        migrations.AddField(
            model_name='operations',
            name='processus_attributions',
            field=models.ManyToManyField(related_name='operations_processus', to='operations.processusattribution', verbose_name="Processus d'attribution des parcelles"),
        ),
        migrations.AddField(
            model_name='projet',
            name='localite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations.localite'),
        ),
        migrations.AddField(
            model_name='operations',
            name='projet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='operations.projet', verbose_name='Projet'),
        ),
        migrations.AddField(
            model_name='positionparcelle',
            name='type_parcelle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions_parcelles', to='operations.typeparcelle', verbose_name='Type de parcelle'),
        ),
        migrations.AddField(
            model_name='operations',
            name='types_parcelles',
            field=models.ManyToManyField(related_name='operations', to='operations.typeparcelle', verbose_name='Types de parcelles'),
        ),
        migrations.AddField(
            model_name='listesparcelles',
            name='usage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parcelles_type', to='operations.typeparcelle', verbose_name='Type de parcelle'),
        ),
    ]
