# Generated by Django 5.1.4 on 2025-01-16 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='date_debut',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projet',
            name='date_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
