# Generated by Django 5.1.4 on 2025-01-16 18:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_alter_projet_date_debut_alter_projet_date_fin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operations',
            name='date_debut_operation',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date et heure de début de l'opération"),
        ),
        migrations.AlterField(
            model_name='operations',
            name='date_fin_operation',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date et heure de fin de l'opération"),
        ),
    ]
