# Generated by Django 5.1.4 on 2025-01-16 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0004_alter_operations_date_debut_operation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listesparcelles',
            name='date_blocage',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listesparcelles',
            name='date_fin_blocage',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
