# Generated by Django 5.1.4 on 2025-01-17 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0005_listesparcelles_date_blocage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listesparcelles',
            name='date_blocage',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de blocage'),
        ),
        migrations.AlterField(
            model_name='listesparcelles',
            name='date_fin_blocage',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de fin de blocage'),
        ),
    ]
