# Generated by Django 5.1.4 on 2025-01-11 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_initial'),
        ('paiements', '0005_remove_paiement_numero_paiement'),
        ('souscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='souscriptioneffectuee',
            name='compte_bancaire',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='paiements.comptebancaire', verbose_name='Compte Bancaire'),
        ),
        migrations.AddField(
            model_name='souscriptioneffectuee',
            name='duree_depot_physique',
            field=models.PositiveIntegerField(null=True, verbose_name='Durée pour le dépôt physique (en jours)'),
        ),
        migrations.AddField(
            model_name='souscriptioneffectuee',
            name='processus_attribution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='operations.processusattribution', verbose_name="Processus d'Attribution"),
        ),
    ]
