# Generated by Django 5.1.4 on 2025-01-11 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_initial'),
        ('paiements', '0005_remove_paiement_numero_paiement'),
        ('souscriptions', '0002_souscriptioneffectuee_compte_bancaire_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='souscriptioneffectuee',
            name='compte_bancaire',
        ),
        migrations.RemoveField(
            model_name='souscriptioneffectuee',
            name='processus_attribution',
        ),
        migrations.AddField(
            model_name='souscriptioneffectuee',
            name='comptes_bancaires',
            field=models.ManyToManyField(related_name='souscriptions', to='paiements.comptebancaire', verbose_name='Comptes Bancaires'),
        ),
        migrations.AddField(
            model_name='souscriptioneffectuee',
            name='processus_attributions',
            field=models.ManyToManyField(related_name='souscriptions', to='operations.processusattribution', verbose_name="Processus d'Attribution"),
        ),
    ]
