# Generated by Django 5.1.4 on 2025-01-16 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('souscriptions', '0003_remove_souscriptioneffectuee_compte_bancaire_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='souscriptioneffectuee',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('confirme', 'Confirmé'), ('annule', 'Annulé')], default='en_attente', max_length=20, verbose_name='Statut'),
        ),
    ]
