# Generated by Django 5.1.4 on 2025-01-17 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('souscriptions', '0005_alter_souscripteurmorale_date_creation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='souscripteurmorale',
            name='adresse',
            field=models.CharField(max_length=255, verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='souscripteurphysique',
            name='adresse',
            field=models.CharField(max_length=255, verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='souscriptioneffectuee',
            name='adresse',
            field=models.CharField(max_length=255, verbose_name='Adresse'),
        ),
    ]
